makoto/blockparty

- test/conference.js
@chris-hughes-SB this is to add spec to catch exception when people did not send correct deposit.
Please sign off.
> Add spec to throw error if it did not send correct Ether

- contracts/Conference.sol
- src/components/BountyInstruction.js
- src/components/ConferenceDetail.js
- src/components/Data.js
- src/components/NetworkLabel.js
- src/components/Participants.js
- src/index.js
Added features
- Takes network name dynamically and point to appropriate etherscan url.
- Displays 'MAINNET', 'TESTNET', 'PRIVATE NET' depending on which network it connects to.
- Metadata (location, dates) are removed from embedded template into Data file.
> Dynamic env

- contracts/Conference.sol
This is to block reentrancy attack vector of the contract.
cc @danielitti @maraoz @jdetychey
> Block reentrancy

- contracts/Conference.sol
Add new events as well as renaming and tidying up existing events. 
FYI: @hacktar
> Tidy up event names

- README.md
- contracts/Conference.sol
- package.json
- public/index.html
- src/components/ConferenceDetail.js
- src/components/Data.js
- src/index.js
- test/conference.js
- truffle.js
- Change test to use `instance.sendTransaction`
- Include jQuery into package
- Upgrade compiler from 0.4.2 to 0.4.8
- Add `ropsten` and `kovan`  network_id
> Truffle320

- README.md
- migrations/2_deploy_contracts.js
- test/conference.js
- truffle.js
> Refactor test

- contracts/Conference.sol
- contracts/ConfirmationRepository.sol
- contracts/InvitationRepository.sol
- contracts/Migrations.sol
- contracts/zeppelin/ownership/Ownable.sol
- log/stress_0002_20170818.log
- log/stress_0020_20170818.log
- log/stress_0100_20170818.log
- log/stress_0200_20170818.log
- package.json
- test/conference.js
- test/stress.js
- plus change stress test to write it into a log
> Truffle346 upgrade

- README.md
- contracts/Conference.sol
- contracts/InvitationRepository.sol
- log/stress_0002.log
- log/stress_0020.log
- log/stress_0100.log
- log/stress_0200.log
- migrations/2_deploy_contracts.js
- scripts/repository.js
- test/conference.js
- test/encryption.js
- test/invitation_repository.js
- test/stress.js
- Make name, deposit, limitOfParticipant configurable at contract initializer
- Allow migration to pass name as configurable
- Fix `confirmation` function bug
> Configurable

- src/components/Data.js
- src/index.js
Changed the way to find event data based on the address specified in the deployed contract.
> Detect by address

- scripts/decrypt.js
- scripts/util/get_block.js
- scripts/uuids.js
- src/components/ConferenceDetail.js
- src/components/Participants.js
- src/index.js
- truffle.js
- Allow decrypt.js to pass starting block number
- Replace price API
- Add UUID generator
- Swallow error when connecting to the wrong network or if contract id does not exist.
- Pass Infurat provider to mainnnet truffle config
> Fix wrong network error

- src/components/FormInput.js
> Fixed typo in confirm attendance

- scripts/history.js
- src/components/Data.js
> Add ether price

- contracts/Conference.sol
> Convert depricated .send() to transfer()

- contracts/Conference.sol
> Convert public to external where possible

- src/components/Instruction.js
- src/components/Participants.js
- Update instruction
- Fix [the problem of ticking users after a name search](https://github.com/makoto/blockparty/issues/145)
> Update how to introduction

- src/components/FormInput.js
- src/components/Participants.js
- Contract owner can add participants as admins
- Admins are marked as *
Fixes https://github.com/makoto/blockparty/issues/144
> Add grant UI

- .solcover.js
- contracts/Conference.sol
- test/conference.js
- test/group_admin.js
From
```
-----------------|----------|----------|----------|----------|----------------|
File             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------|----------|----------|----------|----------|----------------|
contracts/      |       96 |     91.3 |     91.3 |    97.59 |                |
Conference.sol |    96.61 |    92.11 |    94.12 |    98.44 |            132 |
GroupAdmin.sol |    93.75 |     87.5 |    83.33 |    94.74 |             44 |
-----------------|----------|----------|----------|----------|----------------|
All files        |       96 |     91.3 |     91.3 |    97.59 |                |
-----------------|----------|----------|----------|----------|----------------|
```
To
```
-----------------|----------|----------|----------|----------|--- …
```
> 100% test coverage

- src/components/FormInput.js
- src/components/Participants.js
- src/index.js
- src/util/participantStatus.js
Fix https://github.com/makoto/blockparty/issues/141
> Fix cancel

- src/index.js
https://github.com/makoto/blockparty/issues/120
> Add dynamic gasPrice setting

- contracts/Conference.sol
- test/conference.js
So that I can pre deploy events when the gas price is low.
> Add changeName
